version: "3.8"

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=${MONGODB_DATABASE:-mydatabase}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-user}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
    ports:
      - '27017:27017'
    networks:
      - collector_network
    restart: unless-stopped
    volumes:
      - mongodb_data:/bitnami/mongodb
  
  oaievals-collector:
    platform: linux/arm64
    build: 
      context: ../
      dockerfile: Dockerfile
    restart: always
    volumes:
      - data_volume:/data
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI:-mongodb:27017}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-mydatabase}
      MONGODB_USERNAME: ${MONGODB_USERNAME:-user}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION:-mycollection}
    ports:
      - "8081:8080"
    networks:
      - collector_network

volumes:
  mongodb_data:
    driver: local
  data_volume:
    driver: local

networks:
  collector_network:
    driver: bridge
