version: "3.8"

services:
  db:
    # platform: linux/arm64
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: my-user
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - collector_network
    restart: unless-stopped
  
  oaievals-collector:
    platform: linux/arm64
    build: 
      context: ../
      dockerfile: Dockerfile
    restart: always
    volumes:
      - data_volume:/data
    depends_on:
      - db
    environment:
      INFLUXDB_HOST: http://db:8086
      INFLUXDB_USER: my-user
      INFLUXDB_TOKEN: WlzWM122bT1CvsLTNsgivIIKWaEBo6F1w2tLzmfaQSEDQ6XQkFhBeSwJCeHBxYGKonhRKCIL8ird9T7CfkSoJw==
      INFLUXDB_ORG: my-org
      INFLUXDB_BUCKET: my-bucket
    ports:
      - "8081:8080"
    networks:
      - collector_network

volumes:
  influxdb_data:
    driver: local
  data_volume:
    driver: local

networks:
  collector_network:
    driver: bridge
